### ISSUE TITLE
Optimize K-D Tree Construction

### ISSUE THREAD

**Issue by minkezhang** [downflux/go-kd#3]
Creating a K-D tree necessitates sorting the same set of data repeatedly as we continue with recursive calls on different splitting planes. This generally leads to suboptimal performance. We should look into different tree construction methods, e.g. the method outlined in

Shevtsov et al. _[Highly Parallel Fast KD-tree Construction for Interactive Ray Tracing of Dynamic Scenes](https://www.researchgate.net/publication/220506832_Highly_Parallel_Fast_KD-tree_Construction_for_Interactive_Ray_Tracing_of_Dynamic_Scenes)_. Computer Graphics Forum, 2007.

**Comment by mbcx4jrh** [comment]
Hi, this gets my vote.
I'm currently watching a simulation running with around 3e6 points - each iteration does 3e6 radial searches and takes 1m27s in total. 1m9s of that is spent creating the tree.
my usage here: https://github.com/mbcx4jrh/CellularForms
This is my first Go project, so I'm of limited use though :o)

**Comment by minkezhang** [comment]
@mbcx4jrh What hardware are you running on? Tree construction of N ~ 1e6 points should take ~10s, which is still pretty slow, but substantially faster than what you're observing. I see your embedded point is the `Cell` [struct](https://github.com/mbcx4jrh/CellularForms/blob/2594e083455e0ecc4c5565e63c0a24a2565d749a/generator/cell.go#L11); have you tried embedding a pointer to this struct instead?

**Comment by mbcx4jrh** [comment]
@minkezhang , I thought that's what i  was doing with :
````Go
	treePoints := make([]point.P, len(cf.cells)) 
	for i := range cf.cells { 
		treePoints[i] = &cf.cells[i]
	}
````

But my Go skills are not exactly brilliant right now...  
I'm on a 2.9GHz i7 2018 MacBook Pro.

**Comment by mbcx4jrh** [comment]
Looked at this - i think you meant do this:
````go
type TreePoint struct {
	p         vector.V
	cellIndex int
}

func (tp TreePoint) P() vector.V {
	return tp.p
}
````

I embedded the index for cell rather than a pointer .. certainly cut the build time for a tree down to 1/3rd the previous amount

**Comment by minkezhang** [comment]
Interesting. Added a test in https://github.com/downflux/go-kd/commit/7816b8893feebf8bbd114ebf9ce4d143330bdef1 to check tree construction times for more complex points. You can run with

```bash
go test -v github.com/downflux/go-kd/kd -bench BenchmarkNew -benchmem 
```

I'm not seeing a significant difference between the two sets of benchmarks. You can check how the slice of points are constructed in [generator.go](https://github.com/downflux/go-kd/blob/7816b8893feebf8bbd114ebf9ce4d143330bdef1/internal/testdata/generator/generator.go#L41).

```bash
=== RUN   TestConsistentK
--- PASS: TestConsistentK (0.00s)
goos: linux
goarch: amd64
pkg: github.com/downflux/go-kd/kd
cpu: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
BenchmarkNew
BenchmarkNew/K=2/N=10000
BenchmarkNew/K=2/N=10000-8         	      58	  18534083 ns/op	 1091058 B/op	   14096 allocs/op
BenchmarkNew/K=2/N=10000/MultiField
BenchmarkNew/K=2/N=10000/MultiField-8         	      72	  16074559 ns/op	 1091056 B/op	   14096 allocs/op
BenchmarkNew/K=2/N=100000
BenchmarkNew/K=2/N=100000-8                   	       3	 340649490 ns/op	10702480 B/op	  134461 allocs/op
BenchmarkNew/K=2/N=100000/MultiField
BenchmarkNew/K=2/N=100000/MultiField-8        	       3	 368438033 ns/op	10702384 B/op	  134460 allocs/op
BenchmarkNew/K=2/N=200000
BenchmarkNew/K=2/N=200000-8                   	       2	1028093772 ns/op	21404400 B/op	  268914 allocs/op
BenchmarkNew/K=2/N=200000/MultiField
BenchmarkNew/K=2/N=200000/MultiField-8        	       2	1046305404 ns/op	21404624 B/op	  268917 allocs/op
BenchmarkNew/K=2/N=300000
BenchmarkNew/K=2/N=300000-8                   	       1	1736738453 ns/op	32990544 B/op	  431029 allocs/op
BenchmarkNew/K=2/N=300000/MultiField
BenchmarkNew/K=2/N=300000/MultiField-8        	       1	1789200941 ns/op	32990640 B/op	  431030 allocs/op
BenchmarkNew/K=2/N=1000000
BenchmarkNew/K=2/N=1000000-8                  	       1	9047572684 ns/op	111183664 B/op	 1475196 allocs/op
BenchmarkNew/K=2/N=1000000/MultiField
BenchmarkNew/K=2/N=1000000/MultiField-8       	       1	9526662694 ns/op	111176432 B/op	 1475092 allocs/op
BenchmarkNew/K=10/N=10000
BenchmarkNew/K=10/N=10000-8                   	      58	  20795923 ns/op	 1091056 B/op	   14096 allocs/op
BenchmarkNew/K=10/N=10000/MultiField
BenchmarkNew/K=10/N=10000/MultiField-8        	      63	  18349883 ns/op	 1091059 B/op	   14096 allocs/op
BenchmarkNew/K=10/N=100000
BenchmarkNew/K=10/N=100000-8                  	       3	 418488290 ns/op	10702864 B/op	  134465 allocs/op
BenchmarkNew/K=10/N=100000/MultiField
BenchmarkNew/K=10/N=100000/MultiField-8       	       3	 437736164 ns/op	10702864 B/op	  134465 allocs/op
BenchmarkNew/K=10/N=200000
BenchmarkNew/K=10/N=200000-8                  	       1	1077923658 ns/op	21405712 B/op	  268929 allocs/op
BenchmarkNew/K=10/N=200000/MultiField
BenchmarkNew/K=10/N=200000/MultiField-8       	       1	1085920755 ns/op	21405712 B/op	  268929 allocs/op
BenchmarkNew/K=10/N=300000
BenchmarkNew/K=10/N=300000-8                  	       1	1830432200 ns/op	32994288 B/op	  431072 allocs/op
BenchmarkNew/K=10/N=300000/MultiField
BenchmarkNew/K=10/N=300000/MultiField-8       	       1	1907625891 ns/op	32994288 B/op	  431072 allocs/op
BenchmarkNew/K=10/N=1000000
BenchmarkNew/K=10/N=1000000-8                 	       1	9393531725 ns/op	111222800 B/op	 1475713 allocs/op
BenchmarkNew/K=10/N=1000000/MultiField
BenchmarkNew/K=10/N=1000000/MultiField-8      	       1	9509715473 ns/op	111222800 B/op	 1475713 allocs/op
PASS
ok  	github.com/downflux/go-kd/kd	72.316s
```

**Comment by mbcx4jrh** [comment]
I'll have a look tomorrow - I'm working my way down a bottle of wine atm (it is 10pm here).
Im just running a long simulation and these are the timings
````
Iterating through 5000000 cells
Average time per cell 19.902µs
Time per iteration    1m39.51208506s
Interface conversion took 290.625124ms
Tree building took 1m14.234043619s
````
interface conversion, in this case, means the construction of the TreePoint array.

At 5e6 cells it's really slowing down (for me) - at 100k cells tree build was only 1/3rd of an iteration.

I need to look into profiling now, looks fairly easy in golang, but again, job for tomorrow

On another related note, when I was expecting to have to write this myself I noticed the wikipedia article mentioned a stochastic method of tree building  (sampling random points to generate the hyperplane) which looked like an interesting method, but I couldn't find any references.



_Maybe I should have picked a simpler problem to learn Go with_
